/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atmgui;

import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author fiyuu
 */
public class cetak_struct extends javax.swing.JFrame {

	/**
	 * Creates new form cetak_struct
	 */
	private final String id = session.getInstance().getUserId();
	private static String kode;
	
	public cetak_struct(String uuid) {
		initComponents();
		cetak_struct.kode = uuid;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                cetak_struct_button = new javax.swing.JButton();
                back_button = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                cetak_struct_button.setText("Cetak Struct");
                cetak_struct_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cetak_struct_buttonActionPerformed(evt);
                        }
                });

                back_button.setText("Back");
                back_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                back_buttonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(cetak_struct_button)
                                .addContainerGap(164, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back_button)
                                .addGap(15, 15, 15))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(cetak_struct_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                .addComponent(back_button)
                                .addGap(26, 26, 26))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void cetak_struct_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetak_struct_buttonActionPerformed
                // TODO add your handling code here:
		DBConnection con = new DBConnection();
		
	try {
		// Create PDF document
		Document document = new Document(PageSize.A4);
		PdfWriter.getInstance(document, new FileOutputStream("output.pdf"));
		document.open();

		// Retrieve data from database
		PreparedStatement stmt = con.connect().prepareStatement("SELECT * FROM transfer WHERE uuid = ?");
		stmt.setString(1, kode);
		
		ResultSet result = stmt.executeQuery();

		// Create table
//		PdfPTable table = new PdfPTable(5);
//		table.setWidthPercentage(100);
//		PdfPCell cell = new PdfPCell(new Paragraph("Transfer Struct \n \n"));
//		cell.setColspan(3);
//		table.addCell(cell);
//		table.addCell("Kode Transfer");
//		table.addCell("Bank Penerima");
//		table.addCell("Jumlah");
//		table.addCell("Penerima");
//		table.addCell("Pengirim");
//		table.addCell("Tanggal");

		// Add data
		if (result.next()) {
		   String bank_penerima = result.getString("bank_penerima");
		   String jumlah = result.getString("jumlah");
		   String penerima = result.getString("penerima");
		   String pengirim = result.getString("pengirim");
		   String tgl = result.getString("tgl");
		   
		   Paragraph para = new Paragraph("Transfer Struct \n \n "
			   + "Kode Transfer \t: " + kode + " \n "
			   + "Bank Penerima \t: " + bank_penerima + "\n "
			   + "Jumlah \t: " + jumlah + "\n "
			   + "Penerima \t: " + penerima + "\n "
			   + "Pengirim \t: " + pengirim + "\n "
			   + "Tanggal \t: " + tgl + "\n "
		   );
			// Add table to document
			document.add(para);
		}
		
		// Close document and database connection
		document.close();
		con.connect().close();
		
		JOptionPane.showMessageDialog(this, "PDF berhasil dibuat");
		
	     } catch (Exception e) {
		e.printStackTrace();
	     }
        }//GEN-LAST:event_cetak_struct_buttonActionPerformed

        private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
                // TODO add your handling code here:
	session.getInstance().setUserId(id);

                dashboard_page dashboard = new dashboard_page();
                dashboard.setLocationRelativeTo(null);
                dashboard.setVisible(true);
                dispose();
        }//GEN-LAST:event_back_buttonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(cetak_struct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(cetak_struct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(cetak_struct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(cetak_struct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new cetak_struct(kode).setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton back_button;
        private javax.swing.JButton cetak_struct_button;
        private javax.swing.JPanel jPanel1;
        // End of variables declaration//GEN-END:variables
}
