/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atmgui;


import java.sql.*;
import java.util.HashMap;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author fiyuu
 */
public class register_page extends javax.swing.JFrame {

	private final DBConnection con;
	/**
	 * Creates new form register_page
	 */
	public register_page() {
		this.con = new DBConnection();
		initComponents();
		setModelList();
	}
	
	private String bankAccountGenerator(){
		Random generator = new Random();
		String startWith = "007";
		String accountNumber = startWith + generator.nextInt(1000000);
		return accountNumber;
	}
	
	private boolean isNumberOnly(String str) {
		String pattern = "^[0-9]+$";
		return str.matches(pattern);
	}
	
	private void setModelList() {
		HashMap<Integer, String> bankMap = new HashMap<>();

		String select_bank = "SELECT  * FROM bank";
		try {
			PreparedStatement statement = con.connect().prepareStatement(select_bank);
			ResultSet resultSet = statement.executeQuery();

			while (resultSet.next()) {
			    int bankId = resultSet.getInt("id");
			    String bankNama = resultSet.getString("nama_bank");
			    bankMap.put(bankId, bankNama);
			}
			
			DefaultComboBoxModel model = new DefaultComboBoxModel();

			model.addElement("Pilih bank anda");
			for (String nama : bankMap.values()) {
				model.addElement(nama);
				bank_comboBox.setModel(model);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                pin_textfield = new javax.swing.JPasswordField();
                register_button = new javax.swing.JButton();
                back_button = new javax.swing.JButton();
                jLabel4 = new javax.swing.JLabel();
                nama_textfield = new javax.swing.JTextField();
                bank_comboBox = new javax.swing.JComboBox<>();
                jLabel5 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel2.setText("ATM REGISTER");

                jLabel3.setText("PIN");

                register_button.setText("Register");
                register_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                register_buttonActionPerformed(evt);
                        }
                });

                back_button.setText("Back");
                back_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                back_buttonActionPerformed(evt);
                        }
                });

                jLabel4.setText("Nama");

                nama_textfield.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nama_textfieldActionPerformed(evt);
                        }
                });

                bank_comboBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bank_comboBoxActionPerformed(evt);
                        }
                });

                jLabel5.setText("Bank");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back_button)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(nama_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(register_button)
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel5))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(bank_comboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(pin_textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                                .addContainerGap(122, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(nama_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bank_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pin_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(26, 26, 26)
                                .addComponent(register_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addComponent(back_button)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
                // TODO add your handling code here:
	String nama = nama_textfield.getText().toUpperCase();
	String pin = new String(pin_textfield.getPassword());
	String bank = (String) bank_comboBox.getSelectedItem();
	Integer jumlah_saldo = 500000;
	Integer no_rekening = Integer.valueOf(bankAccountGenerator());
	
	DBConnection con = new DBConnection();
	login_page login = new login_page();
	
	if (!isNumberOnly(pin)) {
		JOptionPane.showMessageDialog(null, "pin harus berupa Number!");
		return;
	}
	
	if (pin.length() < 5 && nama.length() < 5) {
		JOptionPane.showMessageDialog(null, "pin dan nama harus lebih dari 5 char");
		return;
	}

	if (pin.isEmpty() && nama.isEmpty()) {
		JOptionPane.showMessageDialog(null, "pin dan nama tidak boleh kosong");
		return;
	}

	String user_pin = "SELECT * FROM user WHERE pin = ?";
	String insert = "INSERT INTO user SET id_bank = ?, jumlah_saldo = ?, nama = ?, no_rekening = ?, pin = ?";
	String select_bank = "SELECT * FROM bank WHERE nama_bank = ?";
	
	try {
		PreparedStatement select_pin = con.connect().prepareStatement(user_pin);
		select_pin.setString(1, pin);

		ResultSet result_pin = select_pin.executeQuery();

		if (result_pin.next()) {
			JOptionPane.showMessageDialog(null, "PIN sudah digunakan!");
			return;
		}
		
		PreparedStatement query_bank = con.connect().prepareStatement(select_bank);
		query_bank.setString(1, bank);

		ResultSet result_bank = query_bank.executeQuery();
		
		Integer id_bank = 0;
		
		if (result_bank.next()) {
			id_bank = result_bank.getInt("id");
		} else {
			JOptionPane.showMessageDialog(null, "Silahkan pilih bank yang Valid!");
			return;
		}
		
		PreparedStatement final_query = con.connect().prepareStatement(insert);
		final_query.setInt(1, id_bank);
		final_query.setInt(2, jumlah_saldo);
		final_query.setString(3, nama);
		final_query.setInt(4, no_rekening);
		final_query.setString(5, pin);

		int final_result = final_query.executeUpdate();
		
		if (final_result > 0) {
			JOptionPane.showMessageDialog(this, "anda berhasil registrasi!");
			login.setLocationRelativeTo(null);
			login.setVisible(true);
			dispose();
		} else {
			JOptionPane.showMessageDialog(this, "anda gagal registrasi!");
			return;
		}
		
		select_pin.close();
		result_pin.close();
		query_bank.close();
		result_bank.close();
		final_query.close();
		con.connect().close();
		
	} catch (SQLException e) {
		e.printStackTrace();
	}
	
	
        }//GEN-LAST:event_register_buttonActionPerformed

        private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
                // TODO add your handling code here:
	login_page login  = new login_page();
	login.setLocationRelativeTo(null);
	login.setVisible(true);
	dispose();
        }//GEN-LAST:event_back_buttonActionPerformed

        private void nama_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_textfieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_nama_textfieldActionPerformed

        private void bank_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bank_comboBoxActionPerformed
	
        }//GEN-LAST:event_bank_comboBoxActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new register_page().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton back_button;
        private javax.swing.JComboBox<String> bank_comboBox;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField nama_textfield;
        private javax.swing.JPasswordField pin_textfield;
        private javax.swing.JButton register_button;
        // End of variables declaration//GEN-END:variables
}
