/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atmgui;

import java.sql.*;
import java.util.UUID;
import javax.swing.JOptionPane;
/**
 *
 * @author fiyuu
 */
public class transfer_page extends javax.swing.JFrame {

	private final String id;
	private final DBConnection con;
	private final String uuid;
	public transfer_page() {
		this.uuid = generateUUID();
		this.con = new DBConnection();
		this.id = session.getInstance().getUserId();
		initComponents();
	}
	
	/**
	 * Creates new form transfer_page
	 */
	private String generateUUID() {
		UUID random = UUID.randomUUID();
		return random.toString();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                no_rekening_textfield = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                jumlah_transfer_textfield = new javax.swing.JTextField();
                transfer_button = new javax.swing.JButton();
                back_button = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel1.setText("Transfer");

                jLabel2.setText("No. Rekening Tujuan");

                jLabel3.setText("Jumlah Transfer");

                jumlah_transfer_textfield.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jumlah_transfer_textfieldActionPerformed(evt);
                        }
                });

                transfer_button.setText("Transfer");
                transfer_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                transfer_buttonActionPerformed(evt);
                        }
                });

                back_button.setText("Back");
                back_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                back_buttonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(162, 162, 162))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(transfer_button)
                                                .addGap(30, 30, 30))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(back_button)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(42, 42, 42)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(no_rekening_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                                        .addComponent(jumlah_transfer_textfield))))
                                .addContainerGap(80, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(no_rekening_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jumlah_transfer_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addComponent(transfer_button)
                                .addGap(18, 18, 18)
                                .addComponent(back_button)
                                .addContainerGap(63, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jumlah_transfer_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_transfer_textfieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jumlah_transfer_textfieldActionPerformed

        private void transfer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfer_buttonActionPerformed
                // TODO add your handling code here:
	String no_rekening = no_rekening_textfield.getText();
	Integer jumlah_transfer = Integer.valueOf(jumlah_transfer_textfield.getText());
	
	if (jumlah_transfer.equals(0)) {
		JOptionPane.showMessageDialog(null, "Isi kan jumlah yang akan di Transfer!");
		return;
	}
	
	String select_no_rekening_tujuan = "SELECT * FROM user WHERE no_rekening = ?";
	
	String select_bank = "SELECT * FROM bank WHERE id = ?";
	
	String select_user_pengirim = "SELECT * FROM user WHERE id = ?";
	
	String transferTo = "INSERT INTO transfer SET uuid = ?, bank_penerima = ?, id_user_pengirim = ?, jumlah = ?, penerima = ?, pengirim = ?, tgl = NOW()";
	
	try {
		// no rekening
		PreparedStatement noRek = con.connect().prepareStatement(select_no_rekening_tujuan);
		noRek.setString(1, no_rekening);
		
		ResultSet result_noRek = noRek.executeQuery();
		
		if (result_noRek.next()) {
			// String noRek_tujuan = result_noRek.getString("no_rekening");
			String id_bank_user = result_noRek.getString("id_bank");
			String nama_penerima = result_noRek.getString("nama");
			
			// bank
			PreparedStatement bank = con.connect().prepareStatement(select_bank);
			bank.setString(1, id_bank_user);

			ResultSet result_bank = bank.executeQuery();
			
			// user pengirim
			PreparedStatement user_pengirim = con.connect().prepareStatement(select_user_pengirim);
			user_pengirim.setString(1, id);

			ResultSet result_user_pengirim = user_pengirim.executeQuery();
			
			String nama_pengirim = "";
			if (result_user_pengirim.next()) {
				nama_pengirim = result_user_pengirim.getString("nama");
				Integer jumlah_saldo = result_user_pengirim.getInt("jumlah_saldo");
				
				if (jumlah_saldo - jumlah_transfer < 50000) {
					JOptionPane.showMessageDialog(null, "Minimal batas sisa saldo anda harus 50.000, anda tidak bisa melakukan penarikan dengan jumlah sisa saldo dibawah 50.000");
					return;
				}
			}
			
			String nama_bank = "";
			if (result_bank.next()) {
				nama_bank = result_bank.getString("nama_bank");
				
			} 
			
			PreparedStatement insert_transfer = con.connect().prepareStatement(transferTo);
			insert_transfer.setString(1, uuid);
			insert_transfer.setString(2, nama_bank);
			insert_transfer.setString(3, id);
			insert_transfer.setInt(4, jumlah_transfer);
			insert_transfer.setString(5, nama_penerima);
			insert_transfer.setString(6, nama_pengirim);
		
			int result_transfer = insert_transfer.executeUpdate();
			if (result_transfer > 0) {
				JOptionPane.showMessageDialog(this, "berhasil Transfer!");
				
				session.getInstance().setUserId(id);
				
				cetak_struct cetakStruct = new cetak_struct(uuid);
				cetakStruct.setLocationRelativeTo(null);
				cetakStruct.setVisible(true);
				dispose();
			}
			
			bank.close();
			result_bank.close();
			user_pengirim.close();
			result_user_pengirim.close();
			insert_transfer.close();
			
			
		} else {
			JOptionPane.showMessageDialog(null, "Nomor Rekening tujuan tidak ada");
			return;
		}
		
		con.connect().close();
		noRek.close();
		result_noRek.close();
		
		
		
	} catch (SQLException e) {
		e.printStackTrace();
	}
        }//GEN-LAST:event_transfer_buttonActionPerformed

        private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
                // TODO add your handling code here:
	session.getInstance().setUserId(id);

	dashboard_page dashboard = new dashboard_page();
	dashboard.setLocationRelativeTo(null);
	dashboard.setVisible(true);
	dispose();
        }//GEN-LAST:event_back_buttonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(transfer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(transfer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(transfer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(transfer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new transfer_page().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton back_button;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField jumlah_transfer_textfield;
        private javax.swing.JTextField no_rekening_textfield;
        private javax.swing.JButton transfer_button;
        // End of variables declaration//GEN-END:variables
}
